from __future__ import annotations

from appv22.extensions.base import ObservationContract, SkillCard

FILE_MANAGEMENT_SKILL = SkillCard(
    skill_id="file_management.model_authored_files",
    extension_id="file_management",
    triggers=(
        "workspace",
        "record",
        "leave",
        "useful",
        "next person",
        "capture",
        "decision",
        "durable file",
        "file",
        "write",
        "checklist",
        "note",
        "notes",
        "onboarding",
        "runbook",
        "stub",
        "create",
        "document",
        "handoff",
    ),
    modes=("START", "THINK", "OBSERVE", "ACT", "VERIFY"),
    summary="Pi-style file workspace tools: observe files, read exact content, and write durable artifacts through explicit tool calls.",
    tool_ids=(
        "file_management.repo_snapshot",
        "file_management.read_file",
        "file_management.write_file",
        "file_management.mkdir",
        "file_management.move_file",
        "file_management.copy_file",
        "file_management.delete_file",
    ),
    instructions=(
        "Act as a Pi-style coding agent: use the available file tools directly through the agent loop.",
        "Use repo_snapshot as durable evidence; cite world://file_management.repo_snapshot/latest instead of replaying broad scans after compaction.",
        "For creation tasks, call file_management.write_file with a safe relative path and complete file content.",
        "For organization tasks, use mkdir, move_file, copy_file, and delete_file directly; keep a manifest only if the user asks for a record.",
        "For vague cleanup or organization requests, infer actions from file-content cues such as move, hold, keep, claimed, or collision; do not touch protected-looking paths.",
        "Prioritize human-authored artifacts such as notes, specs, markdown docs, and run logs over machine/session traces; hold keep_* files and machine/session traces unless the user explicitly asks to move them.",
        "Use common destinations when the user asks to organize: standup or team notes under docs/, specs under docs/spec.md unless that destination is already claimed, and run.log files under artifacts/logs/run.log.",
        "For cleanup or organization, prefer move_file over copy_file unless the user asks to preserve the original source; copy_file means duplicate/preserve, not cleanup.",
        "When the user asks to remove obvious junk, call file_management.delete_file on clear junk paths before writing the record, and include those paths in a deletions array in the manifest.",
        "Complete all clear move/copy actions before writing the final record; do not finalize after only one clear action if other explicit move cues remain.",
        "When multiple sources have a colliding basename, the first clear colliding source claims the common destination if that destination does not already exist; hold later colliding sources in place and record why.",
        "When the user asks to keep a record of file organization, write docs/workspace_manifest.json with moves, held, and collisions arrays after the file actions.",
        "Do not emit finalize for an organization task that asks to keep a record until docs/workspace_manifest.json has been written through file_management.write_file.",
        "When repo_snapshot.payload.text_previews contains notes or context, preserve the concrete domain terms from those previews in the created artifact.",
        "If source text marks facts as obsolete, fake, stale, or do-not-use, do not copy those facts into the created artifact unless the user explicitly asks for an exclusions list.",
        "Do not invent cleanup, move files, or write manifests unless the user actually asks for that work.",
        "Reason internally; mutations happen through explicit tool calls.",
    ),
    observation_contract=ObservationContract(
        evidence_refs=("world://file_management.repo_snapshot/latest",),
        evidence_kinds=("file_management.repo_snapshot",),
        preferred_tool_id="file_management.repo_snapshot",
    ),
)
