"""appv22 port of pi's `ai` package (provider/model abstraction + streaming)."""

from appv22.ai.event_stream import (
    AssistantMessageEventStream,
    EventStream,
    create_assistant_message_event_stream,
)
from appv22.ai.models import (
    calculate_cost,
    get_model,
    get_models,
    get_providers,
    register_model,
    reset_models,
)
from appv22.ai.overflow import is_context_overflow
from appv22.ai.register_builtins import register_builtin_providers
from appv22.ai.stream import (
    ApiProvider,
    complete,
    complete_simple,
    complete_simple_sync,
    complete_sync,
    get_api_provider,
    register_api_provider,
    reset_api_providers,
    stream,
    stream_simple,
)
from appv22.ai.types import (
    AssistantMessage,
    AssistantMessageEvent,
    Context,
    Cost,
    DoneEvent,
    ErrorEvent,
    ImageContent,
    Message,
    Model,
    SimpleStreamOptions,
    StreamOptions,
    TextContent,
    ThinkingContent,
    Tool,
    ToolCall,
    ToolResultMessage,
    Usage,
    UserMessage,
    empty_usage,
    now_ms,
)

__all__ = [
    "ApiProvider",
    "AssistantMessage",
    "AssistantMessageEvent",
    "AssistantMessageEventStream",
    "Context",
    "Cost",
    "DoneEvent",
    "ErrorEvent",
    "EventStream",
    "ImageContent",
    "Message",
    "Model",
    "SimpleStreamOptions",
    "StreamOptions",
    "TextContent",
    "ThinkingContent",
    "Tool",
    "ToolCall",
    "ToolResultMessage",
    "Usage",
    "UserMessage",
    "calculate_cost",
    "complete",
    "complete_simple",
    "complete_simple_sync",
    "complete_sync",
    "create_assistant_message_event_stream",
    "empty_usage",
    "get_api_provider",
    "get_model",
    "get_models",
    "get_providers",
    "is_context_overflow",
    "now_ms",
    "register_api_provider",
    "register_builtin_providers",
    "register_model",
    "reset_api_providers",
    "reset_models",
    "stream",
    "stream_simple",
]
